theme: jekyll-theme-midnight
title: Michelle's homepage
description: Biomedical Engineer with knowledge in Computing, Software, AI, and Epidemiology. Bookmark this to keep an eye on my project updates!
